site_name: Asyncio Pool NG
repo_url: https://github.com/smithk86/asyncio-pool-ng
repo_name: smithk86/asyncio-pool-ng
site_url: https://smithk86.github.io/asyncio-pool-ng
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
nav:
  - "index.md"
plugins:
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            show_source: false
            docstring_style: google
            show_root_full_path: false
watch:
  - asyncio_pool
