[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = ["pre-commit", "mypy", "pytest", "pytest-asyncio", "pytest-mypy"]
docs = ["zensical", "mkdocstrings-python"]

[project]
authors = [{ name = "Kyle Smith", email = "smithk86@smc3.com" }]
classifiers = [
    "Intended Audience :: Developers",
    "Framework :: AsyncIO",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = []
description = "A managed pool of coroutine functions."
license = { file = "LICENSE" }
name = "asyncio-pool-ng"
readme = "README.md"
requires-python = ">=3.12,<4"
version = "0.9.0-dev"

[project.urls]
documentation = "https://smithk86.github.io/asyncio-pool-ng"
homepage = "https://github.com/smithk86/asyncio-pool-ng"
repository = "https://github.com/smithk86/asyncio-pool-ng"

[tool.hatch.build.targets.wheel]
packages = ["asyncio_pool"]

[tool.mypy]
packages = ["asyncio_pool", "tests"]
strict = true

[tool.pytest.ini_options]
addopts = "--mypy"
testpaths = ["tests"]

[tool.ruff]
exclude = ["__pycache__", "venv", ".venv"]
line-length = 120
target-version = 'py312'

[tool.ruff.lint]
ignore = [
    "A003",  # flake8-builtins - class attribute {name} is shadowing a python builtin
    "B010",  # flake8-bugbear - do not call setattr with a constant attribute value
    "D100",  # pydocstyle - missing docstring in public module
    "D101",  # pydocstyle - missing docstring in public class
    "D102",  # pydocstyle - missing docstring in public method
    "D103",  # pydocstyle - missing docstring in public function
    "D104",  # pydocstyle - missing docstring in public package
    "D105",  # pydocstyle - missing docstring in magic method
    "D106",  # pydocstyle - missing docstring in public nested class
    "D107",  # pydocstyle - missing docstring in __init__
    "D202",  # pydocstyle - no blank lines allowed after function docstring
    "D205",  # pydocstyle - 1 blank line required between summary line and description
    "D415",  # pydocstyle - first line should end with a period, question mark, or exclamation point
    "E501",  # pycodestyle line too long, handled by black
    "UP037", # pyupgrade - removes quotes from type annotation
]
select = [
    "A",   # flake8-builtins
    "B",   # flake8-bugbear
    "BLE", # flake8-blind-except
    "C4",  # flake8-comprehensions
    "C90", # mccabe
    "D",   # pydocstyle
    "DJ",  # flake8-django
    "DTZ", # flake8-datetimez
    "E",   # pycodestyle errors
    "ERA", # eradicate
    "EXE", # flake8-executable
    "F",   # pyflakes
    "G",   # flake8-logging-format
    "I",   # isort
    "ICN", # flake8-import-conventions
    "ISC", # flake8-implicit-str-concat
    "N",   # pep8-naming
    "PIE", # flake8-pie
    "PLC", # pylint - convention
    "PLE", # pylint - error
    "PLW", # pylint - warning
    "PTH", # flake8-use-pathlib
    "Q",   # flake8-quotes
    "RET", # flake8-return
    "RUF", # Ruff-specific rules
    "S",   # flake8-bandit
    "SIM", # flake8-simplify
    "T10", # flake8-debugger
    "T20", # flake8-print
    "TCH", # flake8-type-checking
    "TID", # flake8-tidy-imports
    "UP",  # pyupgrade
    "W",   # pycodestyle - warning
    "YTT", # flake8-2020
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.*" = ["BLE001", "S101"]
"tests/loadtest.py" = ["T201"]

[tool.ruff.lint.pydocstyle]
convention = "google"
